#!/usr/bin/env python3
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ERROR_H = ROOT / "src" / "shared" / "types" / "Error.h"
OUTPUT = ROOT / "docs" / "quick-reference" / "error-codes-list.md"


def extract_error_codes(text: str):
    enum_match = re.search(r"enum\s+class\s+ErrorCode\s*:\s*int32\s*{(.*?)};", text, re.S)
    if not enum_match:
        raise RuntimeError("ErrorCode enum not found")

    body = enum_match.group(1)
    codes = []
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        line = line.split("//", 1)[0].strip()
        match = re.match(r"([A-Za-z0-9_]+)\s*=\s*([0-9]+)\s*,?$", line)
        if match:
            name, value = match.group(1), match.group(2)
            codes.append((name, value))
    return codes


def render_markdown(codes):
    lines = [
        "# ErrorCode List (Auto Generated)",
        "",
        f"Source: `{ERROR_H.relative_to(ROOT).as_posix()}`",
        f"Generator: `{(ROOT / 'scripts' / 'generate_error_codes.py').relative_to(ROOT).as_posix()}`",
        "",
        "Do not edit this file manually. Run the generator to update it.",
        "",
        "| Name | Value |",
        "| --- | --- |",
    ]
    for name, value in codes:
        lines.append(f"| `{name}` | `{value}` |")
    lines.append("")
    return "\n".join(lines)


def main():
    text = ERROR_H.read_text(encoding="utf-8")
    codes = extract_error_codes(text)
    OUTPUT.write_text(render_markdown(codes), encoding="utf-8")


if __name__ == "__main__":
    main()
